# Generated by Django 5.1.15 on 2026-06-28 12:31

import apps.imports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, upload_to=apps.imports.models.import_upload_to)),
                ('sheet', models.CharField(blank=True, max_length=255)),
                ('header_row', models.PositiveIntegerField(default=0)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('parsing', 'Парсинг'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match_progress', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Смета',
                'verbose_name_plural': 'Сметы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=512)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('material_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('installation_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('match_status', models.CharField(choices=[('unmatched', 'Не сопоставлена'), ('matched', 'Сопоставлена'), ('no_match', 'Без соответствия')], default='unmatched', max_length=16)),
                ('match_source', models.CharField(blank=True, choices=[('auto', 'Автоматически'), ('manual', 'Вручную')], max_length=8)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='catalog.catalogproduct')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.estimate')),
            ],
            options={
                'verbose_name': 'Позиция сметы',
                'verbose_name_plural': 'Позиции сметы',
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project'),
        ),
    ]
