# Generated by Django 5.1.15 on 2026-06-28 12:31

import apps.imports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, upload_to=apps.imports.models.import_upload_to)),
                ('sheet', models.CharField(blank=True, max_length=255)),
                ('header_row', models.PositiveIntegerField(default=0)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('parsing', 'Парсинг'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('article', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_items', to='catalog.catalogproduct')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricelists.pricelist')),
            ],
            options={
                'verbose_name': 'Позиция прайс-листа',
                'verbose_name_plural': 'Позиции прайс-листа',
                'ordering': ['row_number'],
            },
        ),
    ]
