# Generated by Django 6.0.6 on 2026-06-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='row_errors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
