# Generated by Django 6.0.6 on 2026-06-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricelists', '0002_pricelist_row_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='match_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
