# Generated by Django 5.1.15 on 2026-06-28 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа товаров',
                'verbose_name_plural': 'Группы товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=128, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('unit', models.CharField(blank=True, max_length=32, verbose_name='Ед. изм.')),
                ('normalized_article', models.CharField(db_index=True, editable=False, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.productgroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Товар каталога',
                'verbose_name_plural': 'Каталог товаров',
                'ordering': ['name'],
            },
        ),
    ]
