# Generated by Django 6.0.6 on 2026-06-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='normalized_article',
        ),
    ]
