# Generated by Django 6.0.6 on 2026-06-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_catalogproduct_normalized_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
