# Generated by Django 5.1.15 on 2026-06-28 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('inn', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать 10 (юр. лицо) или 12 (ИП) цифр.', regex='^\\d{10}(\\d{2})?$')], verbose_name='ИНН')),
                ('currency', models.CharField(choices=[('RUB', '₽ RUB'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('CNY', '¥ CNY')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
    ]
